name: Teste Automatico
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Rodar teste simples
        run: echo "O sistema de agendamento esta funcionando!"
# Apenas forçando o gatilho do cron
