name: Leitor DO
on:
  schedule:
    - cron: '0 10 * * *' # Isso roda às 07:00 da manhã (Horário de Brasília)
  workflow_dispatch: # Permite rodar manualmente a qualquer momento

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install requests playwright
          playwright install chromium
      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python .github/workflows/leitorDO.py
